name: CI

on:
  push:
  pull_request:

jobs:
  run-tests:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python-version:
        - "3.7"
        - "3.8"
        - "3.9"

    name: Test
    runs-on: ${{matrix.os}}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-versions: ${{matrix.python-version}}

      - name: Set up venv
        run: python3 -m venv venv 

      - name: Source venv
        run: source venv/bin/activate 
      
      - name: Install dependencies
        run: |
          python3 -m pip install flask==2.3.3 flask_sqlalchemy flask_bootstrap flask_wtf wtforms_alchemy flask_migrate flask_appbuilder==4.5.0 flask_paginate Levenshtein
          python3 -m pip install coverage

      - name: Run tests with coverage
        run: |
          coverage run -m unittest discover

      - name: Generate coverage report
        run: coverage xml

      - name: Upload coverage report
        uses: actions/upload-artifact@v2
        with:
          name: coverage-report
          path: ./coverage.xml
