name: CI

on:
  push:
  pull_request:

jobs:
  run-tests:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version:
        - "3.7"
        - "3.8"
        - "3.9"

    name: Test
    runs-on: ${{matrix.os}}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-versions: ${{matrix.python-versions}}

      - name: Set up venv
        run: python3 -m venv venv |
        source venv/bin/activate 
      
      - name: Install dependences
        run: python3 -m pip install flask flask_sqlalchemy flask_bootstrap flask_wtf wtforms_alchemy flask_migrate flask_appbuilder
        # run: python3 -m pip install flask flask_sqlalchemy flask_bootstrap flask_wtf wtforms_alchemy  flask_appbuilder flask_paginate Levenshtein flask_uploads

      
      - name: Run tests
        run: python3 -m unittest
